# Generated by Django 3.2.3 on 2021-06-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/R0805d07b70205857a5d6123…WX66c3zxNDjukANZCb9EhIWD0PJP4%3d&risl=&pid=ImgRaw', max_length=500),
        ),
    ]
